# Generated by Django 4.2 on 2025-11-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreclass',
            name='max_grade',
        ),
        migrations.RemoveField(
            model_name='oreclass',
            name='min_grade',
        ),
        migrations.AddField(
            model_name='oreclass',
            name='fe_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oreclass',
            name='fe_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oreclass',
            name='mgo_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oreclass',
            name='mgo_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oreclass',
            name='ni_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oreclass',
            name='ni_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oreclass',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
