# Generated by Django 4.2 on 2025-09-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineproductions',
            name='direct',
            field=models.CharField(blank=True, default='No', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='oreproductions',
            name='direct',
            field=models.CharField(blank=True, default='No', max_length=15, null=True),
        ),
    ]
