# Generated by Django 4.2 on 2025-09-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingofficial',
            name='sm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
