# Generated by Django 4.2 on 2025-10-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineReserve',
            fields=[
                ('id_reserve', models.AutoField(primary_key=True, serialize=False)),
                ('block_model', models.CharField(blank=True, max_length=100, null=True)),
                ('pit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=50, null=True)),
                ('ore_type', models.CharField(blank=True, choices=[('ALL', 'All Type'), ('LIM', 'Limonite'), ('SAP', 'Saprolite')], default='ALL', max_length=20, null=True)),
                ('tonnage', models.FloatField(default=0.0)),
                ('ni_grade', models.FloatField(default=0.0)),
                ('fe_grade', models.FloatField(default=0.0)),
                ('co_grade', models.FloatField(default=0.0)),
                ('mgo_grade', models.FloatField(default=0.0)),
                ('sio2_grade', models.FloatField(default=0.0)),
                ('strip_ratio', models.FloatField(default=0.0)),
                ('cutoff_grade', models.FloatField(default=1.0)),
                ('date_estimated', models.DateField()),
                ('estimated_by', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mine_reserve',
                'ordering': ['-date_estimated'],
            },
        ),
    ]
