# Generated by Django 4.2 on 2026-03-01 00:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStockDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('incoming', models.FloatField(default=0)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mine_stock_fuel',
            },
        ),
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('milimeter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mine_rainfall',
            },
        ),
        migrations.CreateModel(
            name='RainfallPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mine_rainfall_point',
            },
        ),
        migrations.AddIndex(
            model_name='rainfallpoint',
            index=models.Index(fields=['name'], name='idx_rainfall_type'),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_rainfall', to='kqms.rainfallpoint'),
        ),
        migrations.AddIndex(
            model_name='fuelstockdaily',
            index=models.Index(fields=['date'], name='mine_stock__date_1da1db_idx'),
        ),
        migrations.AddIndex(
            model_name='rainfall',
            index=models.Index(fields=['date'], name='idx_rainfall'),
        ),
    ]
