# Generated by Django 4.2 on 2026-01-23 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceminesloading',
            name='extra_properties',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
