# Generated by Django 4.2 on 2025-10-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingbarging',
            old_name='code_fix_batch',
            new_name='code_monitoring',
        ),
        migrations.AddField(
            model_name='sampleproductions',
            name='sale_monitoring',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='al2o3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='cao',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='co',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='cr2o3',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='fe',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='mc',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='mgo',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='mno',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='ni',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='sio2',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='sm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='tonnage',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name='sampleproductions',
            index=models.Index(fields=['sale_monitoring'], name='samples_pro_sale_mo_6884bd_idx'),
        ),
    ]
