# Generated by Django 4.2 on 2026-03-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0002_fuelstockdaily_rainfall_rainfallpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rainfall',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rainfallpoint',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
