# Generated by Django 4.2 on 2025-09-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0002_sellingofficial_sm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingofficial',
            name='sm',
        ),
    ]
