# Generated by Django 4.2 on 2025-09-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0002_alter_mineproductions_direct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumetruckfactoradjustment',
            name='bucket_original',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='volumetruckfactoradjustment',
            name='bucket_updated',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
