# Generated by Django 4.2 on 2025-09-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0003_volumetruckfactoradjustment_bucket_original_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='volumetruckfactoradjustment',
            unique_together={('date_start', 'date_end', 'category', 'vendors', 'loading_point', 'type_truck', 'material', 'bucket_updated')},
        ),
    ]
