# Generated by Django 4.2 on 2025-09-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0003_remove_sellingofficial_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingbarging',
            name='status_barging',
            field=models.CharField(blank=True, default='Draft', max_length=50, null=True),
        ),
    ]
