# Generated by Django 4.2 on 2025-09-09 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0004_alter_volumetruckfactoradjustment_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oreproductions',
            old_name='hauler_plan',
            new_name='fleet',
        ),
    ]
