# Generated by Django 4.2 on 2025-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0005_rename_hauler_plan_oreproductions_fleet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oreproductions',
            old_name='fleet',
            new_name='hauler_plan',
        ),
    ]
