# Generated by Django 4.2 on 2025-06-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0005_domemergeview_domestatuscloseview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mineProductionsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateField(blank=True, default=None, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('vendors', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('loader', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('hauler', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('hauler_class', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('sources_area', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('loading_point', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dumping_point', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dome_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('category_mine', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('time_loading', models.TimeField(blank=True, default=None, null=True)),
                ('time_dumping', models.TimeField(blank=True, default=None, null=True)),
                ('mine_block', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('from_rl', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('to_rl', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('rl', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('nama_material', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ritase', models.IntegerField(blank=True, default=None, null=True)),
                ('bcm', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('task_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('left_date', models.IntegerField(blank=True, default=None, null=True)),
                ('t_load', models.IntegerField(blank=True, default=None, null=True)),
                ('no_production', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('hauler_type', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('ref_material', models.CharField(blank=True, default=None, max_length=110, null=True)),
                ('ref_truck', models.CharField(blank=True, default=None, max_length=125, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'mine_productions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mineQuickProductionsView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateField(blank=True, default=None, null=True)),
                ('vendors', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('loader', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('hauler', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('hauler_class', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('sources_area', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('loading_point', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dumping_point', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pile_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('distance', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('category_mine', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('mine_block', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('from_rl', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('to_rl', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('rl', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('nama_material', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ritase', models.IntegerField(blank=True, default=None, null=True)),
                ('bcm', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('bcm_total', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage_total', models.FloatField(blank=True, default=None, null=True)),
                ('time_loading', models.IntegerField(blank=True, default=None, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('hauler_type', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('ref_materials', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('ref_plan_truck', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('no_production', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('task_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('left_date', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'mine_quick_productions_v',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['type_table']},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='order_slug',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='type_table',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
