# Generated by Django 4.2 on 2025-06-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0006_mineproductionsview_minequickproductionsview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadLog',
        ),
        migrations.AddField(
            model_name='taskimports',
            name='duplicate_file_path',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
