# Generated by Django 4.2 on 2025-09-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0006_rename_fleet_oreproductions_hauler_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oreproductions',
            name='hauler_plan',
        ),
    ]
