# Generated by Django 4.2 on 2025-06-29 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0007_delete_uploadlog_taskimports_duplicate_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanggal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_date', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tanggal',
            },
        ),
        migrations.CreateModel(
            name='TanggalJam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_time', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tanggal_jam',
            },
        ),
    ]
