# Generated by Django 4.2 on 2025-06-29 05:24

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0008_tanggal_tanggaljam'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceminesdome',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='sourceminesdumping',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
