# Generated by Django 4.2 on 2025-07-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0009_sourceminesdome_geometry_sourceminesdumping_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='allowed_groups',
        ),
        migrations.AddField(
            model_name='oreproductions',
            name='fleet',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='oreproductions',
            name='hauler_plan',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='allowed_group_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
