# Generated by Django 4.2 on 2025-07-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0010_remove_tasklist_allowed_groups_oreproductions_fleet_and_more'),
    ]

    operations = [
    ]
