# Generated by Django 4.2 on 2025-07-08 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0011_migrate_allowed_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='label',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='icon_svg',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='key',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='section_title',
        ),
        migrations.AddField(
            model_name='menu',
            name='allowed_group_names',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kqms.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
