# Generated by Django 4.2 on 2025-07-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0012_rename_label_menu_title_remove_menu_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_category',
            field=models.BooleanField(default=False),
        ),
    ]
