# Generated by Django 4.2 on 2025-07-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0014_mineproductions_idx_mineprod_dedupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='open_new_tab',
            field=models.BooleanField(default=False),
        ),
    ]
