# Generated by Django 4.2 on 2025-07-28 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0015_menu_open_new_tab'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratorySamples',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_received', models.DateField(blank=True, default=None, null=True)),
                ('time_received', models.TimeField(blank=True, default=None, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('waybill_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('qty_sample', models.IntegerField(blank=True, default=None, null=True)),
                ('sample_id', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('mral_order', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('roa_order', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('job_number', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('sample_wet', models.IntegerField(blank=True, default=0, null=True)),
                ('sample_final', models.IntegerField(blank=True, default=0, null=True)),
                ('sample_press', models.IntegerField(blank=True, default=0, null=True)),
                ('sample_analysis', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'laboratory_samples',
            },
        ),
    ]
