# Generated by Django 4.2 on 2025-07-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0016_laboratorysamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorysamples',
            name='sections',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
