# Generated by Django 4.2 on 2025-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0017_laboratorysamples_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorysamples',
            name='priority',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
