# Generated by Django 4.2 on 2025-07-30 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0018_laboratorysamples_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BargePort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('port_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'master_barge_port',
            },
        ),
        migrations.CreateModel(
            name='BargeUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barge_code', models.CharField(max_length=25, unique=True)),
                ('barge_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('capacity', models.FloatField(blank=True, default=None, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'master_barge',
            },
        ),
        migrations.CreateModel(
            name='SellingBarging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_barge_in', models.DateField(blank=True, default=None, null=True)),
                ('date_barge_out', models.DateField(blank=True, default=None, null=True)),
                ('barge_code', models.IntegerField(blank=True, default=None, null=True)),
                ('barging_load_loc', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('barging_unload_loc', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('id_material', models.IntegerField(blank=True, default=None, null=True)),
                ('id_stockpile', models.IntegerField(blank=True, default=None, null=True)),
                ('id_pile', models.IntegerField(blank=True, default=None, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('ritase', models.IntegerField(blank=True, default=None, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('ton_barge_load', models.FloatField(blank=True, default=None, null=True)),
                ('ton_barge_unload', models.FloatField(blank=True, default=None, null=True)),
                ('fill_adjust', models.FloatField(blank=True, default=None, null=True)),
                ('batch', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('nota', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('id_factory', models.IntegerField(blank=True, default=None, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('code_batch', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('code_batch_pulp', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('surv_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_fix_batch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_barging', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('haulage_code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('date_barging', models.DateField(blank=True, default=None, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('sale_dome', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ore_sellings_barging',
            },
        ),
    ]
