# Generated by Django 4.2 on 2025-08-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0019_bargeport_bargeunits_sellingbarging'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbarging',
            name='time_hauling',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
