# Generated by Django 4.2 on 2025-08-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0020_sellingbarging_time_hauling'),
    ]

    operations = [
        migrations.AddField(
            model_name='bargeport',
            name='active',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='bargeunits',
            name='active',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbarging',
            name='surv_order',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
