# Generated by Django 4.2 on 2025-08-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0021_bargeport_active_bargeunits_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingbarging',
            name='surv_order',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
