# Generated by Django 4.2 on 2025-08-03 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0022_alter_sellingbarging_surv_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockfactories',
            old_name='capasity',
            new_name='capacity',
        ),
    ]
