# Generated by Django 4.2 on 2025-08-03 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0023_rename_capasity_stockfactories_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingbarging',
            old_name='code_barging',
            new_name='code_lot',
        ),
        migrations.RemoveField(
            model_name='sellingbarging',
            name='haulage_code',
        ),
    ]
