# Generated by Django 4.2 on 2025-08-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0024_rename_code_barging_sellingbarging_code_lot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingDetailsBargingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_barge_in', models.DateField(blank=True, default=None, null=True)),
                ('date_barge_out', models.DateField(blank=True, default=None, null=True)),
                ('barge_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('barging_load_loc', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('barging_unload_loc', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('dome', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stockpile', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('ritase', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('ton_barge_load', models.FloatField(blank=True, default=None, null=True)),
                ('ton_barge_unload', models.FloatField(blank=True, default=None, null=True)),
                ('fill_adjust', models.FloatField(blank=True, default=None, null=True)),
                ('batch', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_batch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_batch_pulp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('surv_order', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_fix_batch', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_lot', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('factory_stock', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('time_hauling', models.TimeField(blank=True, default=None, null=True)),
                ('nota', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sale_dome', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'details_selling_barging',
                'managed': False,
            },
        ),
    ]
