# Generated by Django 4.2 on 2025-08-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0025_sellingdetailsbargingview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingbarging',
            old_name='code_batch',
            new_name='code_batch_ex',
        ),
        migrations.RemoveField(
            model_name='sellingbarging',
            name='ritase',
        ),
        migrations.AddField(
            model_name='sellingbarging',
            name='code_batch_in',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
