# Generated by Django 4.2 on 2025-08-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0026_rename_code_batch_sellingbarging_code_batch_ex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellingOfficialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_selling', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('code_surveyor', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name_surveyor', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('discharging_port', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('so_number', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('product_code', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('ni', models.FloatField(blank=True, default=None, null=True)),
                ('co', models.FloatField(blank=True, default=None, null=True)),
                ('al2o3', models.FloatField(blank=True, default=None, null=True)),
                ('cao', models.FloatField(blank=True, default=None, null=True)),
                ('cr2o3', models.FloatField(blank=True, default=None, null=True)),
                ('fe', models.FloatField(blank=True, default=None, null=True)),
                ('mgo', models.FloatField(blank=True, default=None, null=True)),
                ('sio2', models.FloatField(blank=True, default=None, null=True)),
                ('mno', models.FloatField(blank=True, default=None, null=True)),
                ('mc', models.FloatField(blank=True, default=None, null=True)),
                ('start_date', models.DateField(blank=True, default=None, null=True)),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'sellings_official_view',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='sellingofficial',
            name='official',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
