# Generated by Django 4.2 on 2025-08-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0027_sellingofficialview_sellingofficial_official'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingofficial',
            name='official_code',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
