# Generated by Django 4.2 on 2025-08-07 02:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0028_sellingofficial_official_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlendingResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blend_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_tonase', models.FloatField()),
                ('target_ni', models.FloatField()),
                ('final_ni', models.FloatField()),
                ('final_fe', models.FloatField(blank=True, null=True)),
                ('final_co', models.FloatField(blank=True, null=True)),
                ('final_mgo', models.FloatField(blank=True, null=True)),
                ('final_al2o3', models.FloatField(blank=True, null=True)),
                ('final_sio2', models.FloatField(blank=True, null=True)),
                ('final_sm', models.FloatField(blank=True, null=True)),
                ('total_used', models.FloatField()),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'ore_sellings_blending',
            },
        ),
        migrations.CreateModel(
            name='BlendingDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pile_id', models.CharField(max_length=50)),
                ('used_tonase', models.FloatField()),
                ('ni', models.FloatField()),
                ('fe', models.FloatField()),
                ('co', models.FloatField(blank=True, null=True)),
                ('mgo', models.FloatField(blank=True, null=True)),
                ('al2o3', models.FloatField(blank=True, null=True)),
                ('sio2', models.FloatField(blank=True, null=True)),
                ('sm', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField()),
                ('blending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='kqms.blendingresult')),
            ],
            options={
                'db_table': 'ore_sellings_blending_detail',
            },
        ),
    ]
