# Generated by Django 4.2 on 2025-08-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0029_blendingresult_blendingdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='planproductions',
            name='lim',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='planproductions',
            name='sap',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='ballast',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='biomass',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='hglo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='hgso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='lglo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='lgso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='mglo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='mgso',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='mws',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='ob',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='quarry',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='topsoil',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='uglo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='planproductions',
            name='waste',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
