# Generated by Django 4.2 on 2025-08-11 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0030_planproductions_lim_planproductions_sap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingBargingTemp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_lot', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('barge_code', models.IntegerField(blank=True, default=None, null=True)),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('time_hauling', models.TimeField(auto_now_add=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('id_material', models.IntegerField(blank=True, default=None, null=True)),
                ('id_stockpile', models.IntegerField(blank=True, default=None, null=True)),
                ('id_pile', models.IntegerField(blank=True, default=None, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('tonnage', models.FloatField(blank=True, default=0, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('no_urut', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ore_sellings_barging_temp',
            },
        ),
    ]
