# Generated by Django 4.2 on 2025-08-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0031_sellingbargingtemp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbargingtemp',
            name='code_sub_auto',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbargingtemp',
            name='code_sub',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
