# Generated by Django 4.2 on 2025-08-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0032_sellingbargingtemp_code_sub_auto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingDetailsBargingTempView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_hauling', models.DateField(blank=True, default=None, null=True)),
                ('time_hauling', models.TimeField(blank=True, default=None, null=True)),
                ('barge_code', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('shift', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('dome', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('stockpile', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('material', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('unit_code', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('tonnage', models.FloatField(blank=True, default=None, null=True)),
                ('code_lot', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code_inc', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_sub', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sale_adjust', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('no_urut', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'details_selling_barging_temp',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='sellingbargingtemp',
            name='time_hauling',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
