# Generated by Django 4.2 on 2025-08-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0033_sellingdetailsbargingtempview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineproductions',
            name='bucket',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
