# Generated by Django 4.2 on 2025-08-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0034_mineproductions_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineadditionfactor',
            old_name='tf_bcm',
            new_name='bucket_capacity',
        ),
        migrations.RenameField(
            model_name='mineadditionfactor',
            old_name='tf_ton',
            new_name='density_bcm',
        ),
        migrations.RenameField(
            model_name='mineadditionfactor',
            old_name='type_truck',
            new_name='type_unit',
        ),
        migrations.AddField(
            model_name='mineadditionfactor',
            name='density_lcm',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
