# Generated by Django 4.2 on 2025-08-21 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0035_rename_tf_bcm_mineadditionfactor_bucket_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineunits',
            old_name='unit_type',
            new_name='unit_class',
        ),
        migrations.AddField(
            model_name='mineunits',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
