# Generated by Django 4.2 on 2025-08-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0036_rename_unit_type_mineunits_unit_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbargingtemp',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
