# Generated by Django 4.2 on 2025-08-23 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0037_sellingbargingtemp_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPlanBarging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField(blank=True, default=None, null=True)),
                ('type_ore', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('type_selling', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('tonnage_plan', models.FloatField(blank=True, default=None, null=True)),
                ('ni_plan', models.FloatField(blank=True, default=None, null=True)),
                ('co_plan', models.FloatField(blank=True, default=None, null=True)),
                ('fe_plan', models.FloatField(blank=True, default=None, null=True)),
                ('sio2_plan', models.FloatField(blank=True, default=None, null=True)),
                ('mgo_plan', models.FloatField(blank=True, default=None, null=True)),
                ('sm_plan', models.FloatField(blank=True, default=None, null=True)),
                ('check_duplicated', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ore_sellings_plan_barging',
            },
        ),
    ]
