# Generated by Django 4.2 on 2025-08-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0038_sellingplanbarging'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingplanbarging',
            name='al2o3_plan',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
