# Generated by Django 4.2 on 2025-08-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0039_sellingplanbarging_al2o3_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingcode',
            name='group_close',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='ritase_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='sublot_close',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellingcode',
            name='truck_factors',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
