# Generated by Django 4.2 on 2025-08-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0040_sellingcode_group_close_sellingcode_ritase_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingbarging',
            name='direct',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sellingbarging',
            name='ritase_group',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='sellingbarging',
            name='status_barging',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbarging',
            name='fill_adjust',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbarging',
            name='ton_barge_load',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbarging',
            name='ton_barge_unload',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sellingbarging',
            name='tonnage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
