# Generated by Django 4.2 on 2025-08-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0041_sellingbarging_direct_sellingbarging_ritase_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingbarging',
            name='nota',
        ),
        migrations.AddField(
            model_name='sellingbarging',
            name='no_input',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
