# Generated by Django 4.2 on 2025-08-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0042_remove_sellingbarging_nota_sellingbarging_no_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='bargingAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField(default=None,null=True,blank=True)),
                ('date_departure', models.DateField(default=None,null=True,blank=True)),
                ('jetty_departure', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('code_lot', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('ritase_ori', models.IntegerField(blank=True, default=None, null=True)),
                ('tonnage_ori', models.FloatField(blank=True, default=None, null=True)),
                ('tonnage_adjust', models.FloatField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('id_user', models.IntegerField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ore_sellings_barging_adjust',
            },
        ),
    ]
