# Generated by Django 4.2 on 2025-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0043_bargingadjust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingbarging',
            name='status_barging',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
