# Generated by Django 4.2 on 2025-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kqms', '0044_alter_sellingbarging_status_barging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingbarging',
            name='ritase_group',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
